Update beer_delete_seed_data.yml

diff --git a/.github/workflows/beer_delete_seed_data.yml b/.github/workflows/beer_delete_seed_data.yml
--- a/.github/workflows/beer_delete_seed_data.yml
+++ b/.github/workflows/beer_delete_seed_data.yml
@@ -144,11 +144,21 @@ jobs:
             cat ${{env.CDK_MODULE}}/requirements.txt
             pip3 install -r  ${{env.CDK_MODULE}}/requirements.txt
         
-        - name: Run python delete tables script
+        - name: Delete company table
           run: |
             (aws dynamodb delete-table --table-name company) || ( echo "table not found" )
+            (aws cloudformation delete-stack --stack-name beer-dynamodb-0-company) || ( echo "stack not found" )
+        
+        - name: Delete company_site table
+          run: |    
             (aws dynamodb delete-table --table-name company_site) || ( echo "table not found" )
+            (aws cloudformation delete-stack --stack-name beer-dynamodb-7-company-site) || ( echo "stack not found" )
+        
+        - name: Delete group table
+          run: |    
             (aws dynamodb delete-table --table-name group) || ( echo "table not found" )
+            (aws cloudformation delete-stack --stack-name beer-dynamodb-10-group) || ( echo "stack not found" )
+            
             
         # AWS IAC cdk deployment
         # Role to deploy as in defined in project.properties file
